swagger: '2.0'
host: 'getpocket.com'
schemes: ['https']
basePath: '/v3'

# This is your document metadata
info:
  version: "0.1.0"
  title: Pocket API

# Describe your paths here
paths:
  # This is a path endpoint. Change it.
  /get:
    # This is a HTTP operation
    get:
      # Describe this verb here. Note: you can use markdown
      description: |
        Retrieving a User's Pocket Data.
      parameters:
        -
          name: consumer_key
          in: query
          description: Your application's Consumer Key
          required: true
          type: string
        -
          name: access_token
          in: query
          description: The user's Pocket access token
          required: true
          type: string
        -
          name: count
          in: query
          description: Only return count number of items
          required: false
          type: integer
        -
          name: offset
          in: query
          description: |
            Used only with count;
            start returning from offset position of results.
          required: false
          type: integer
      responses:
        200:
          description: Successful response
          schema:
              $ref: '#/definitions/items'

definitions:
  items:
    type: object
    properties:
      status:
        type: integer
      list:
        type: object
